version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "jeanmcdowell"
    labels:
      - "type: chore"
      - "status: ready"
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
          - "eslint-config*"
          - "eslint-plugin*"
      typescript:
        patterns:
          - "typescript"
          - "ts-node"
          - "@types/*"
      testing:
        patterns:
          - "vitest"
          - "jsdom"
          - "@vitest/*"
          - "@testing-library/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "jeanmcdowell"
    labels:
      - "type: chore"
      - "status: ready"
    groups:
      actions:
        patterns:
          - "*"
